apiVersion: apps/v1
kind: Deployment
metadata:
  name: photosapplication-deployment
  labels:
    app: photos
spec:
  replicas: 3
  selector:
    matchLabels:
      app: photos
  template:
    metadata:
      labels:
        app: photos
    spec:
      containers:
      - name: photos-application
        image: contreg01aks.azurecr.io/contreg01aks:latest
        ports:
        - containerPort: 80
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: photosapplication-service
spec:
  selector:
    app: photos
  ports:
    - port: 8000
      targetPort: 80
  type: LoadBalancer
